### ISSUE TITLE
초기 데이터 생성방법

### ISSUE THREAD

**Issue by dohvis** [Leop0ld/invest_house#2]
https://github.com/Leop0ld/invest_house/blob/master/shell_code.txt

쉘코드라뇨..ㅋㅋㅋㅋㅋㅋ
Django에는 [fixture](https://docs.djangoproject.com/en/1.10/howto/initial-data/) 라는 기능이 있습니다. 혹은 [django-extensions](https://github.com/django-extensions/django-extensions)의 runscript 기능을 사용해서 https://github.com/nerogit/sunrinio-legacy/blob/master/scripts/init_data.py 이렇게 해줄수도 있고요

**Comment by dohvis** [comment]
https://github.com/vandersonmota/model_mommy 써본적은 없지만 이런것도..

**Comment by myungseokang** [comment]
:thumbsup:

**Comment by EDCMTV** [comment]
음 이거는 djangorestframework 같은 것 아닌가요?
저는 Django 쉘에 코드를 복붙하면 데이터가 생긴다는 의미에서 하기는 했습니다
혹시 자세한 설명해주실 수 있을까요...
저가 장고를 잘 몰라서 하하

**Comment by dohvis** [comment]
아니 왜 점점 저 파일이 늘어나요ㅠㅠ

**Comment by myungseokang** [comment]
shell_code.txt 삭제했슴니당~
