### ISSUE TITLE
커밋 로그

### ISSUE THREAD

**Issue by dohvis** [Leop0ld/invest_house#5]
**커밋의 단위가 들쭉날쭉함**
- 커밋을 잘 나눠야 되는 이유는 `git blame` 같은 기능을 사용해 버그터졌을때 어느 커밋에서 터졌는지, 누가 그 코드 커밋했는지 알아보기 위해
- `~~하다맘`, `~~하는중` 이렇게 한 작업이 끝나지 않았을때 커밋ㄴㄴ
  - 심심할때 코드리뷰좀 하려하는데 커밋 단위가 애매해서 커밋을 봤을때 무슨 코드를 더한 커밋인지 명확하지 않아서 리뷰가 힘듬ㅠㅠ

**Comment by myungseokang** [comment]
덕분에 많이 배워감니다! 감사함니다

**Comment by jun0jang** [comment]
아하 이제부터 유의하겠습니다
